

apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: olympics-db
  namespace: flexagon
  labels:
    run: olympics-db
spec:
  selector:
      matchLabels:
        run: olympics-db
  serviceName: "olympics-db-svc"
  replicas: 1
  template:
    metadata:
      labels:
        run: olympics-db
    spec:
      volumes:
       - name: dshm
         emptyDir:
           medium: Memory    
      containers:
      - image: eugeneflexagon/olympics-db
        volumeMounts:
           - mountPath: /dev/shm
             name: dshm
        imagePullPolicy: Always
        name: olympics-db
        ports:
        - containerPort: 1521
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: olympics-db-svc
  namespace: flexagon
spec:
  selector:
    run: olympics-db
  ports:
    - port: 1521
      targetPort: 1521
  clusterIP: None